resource: "http://localhost:3000/testing/software"
host: "http://localhost:3000"

query: >
  SELECT DISTINCT * WHERE {
      ?s <http://schema.org/name> ?name .
      OPTIONAL {?s <http://schema.org/description> ?description} .
      OPTIONAL {?s <http://schema.org/logo> ?logo} .
    }

sheet:
  id: "ABCD1234"
  name: "Sheet1"
  interval: 10000