resource: "http://localhost:3000/example/software"
host: "http://localhost:3000"

fields:
  required:
    - name: "<http://schema.org/name>"
  optional:
    - description: "<http://schema.org/description>"
    - logo: "<http://schema.org/logo>"

sheet:
  id: "ABCD1234"
  name: "Sheet1"
  interval: 10000